title: Skittly Documentation
description: Documentation Hub for Skittly Projects
baseurl: "/skittly-docs" # or "" if deploying to root
url: "https://timedilationv2.github.io"
theme: minima
markdown: kramdown
